#ifndef PLATFORM_CHIBIOS3_PUBLIC_TINA_BUILD_INFO_H
#define PLATFORM_CHIBIOS3_PUBLIC_TINA_BUILD_INFO_H

#include <tina/helper/macros.h>

#ifdef TURAG_USE_BUILDINFO

TURAG_C_API
void turag_build_info(void);

#endif // TURAG_USE_BUILDINFO

#endif // PLATFORM_CHIBIOS3_PUBLIC_TINA_BUILD_INFO_H
