#ifndef PLATFORM_CHIBIOS3_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H
#define PLATFORM_CHIBIOS3_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H

/// ASCII-Zeichen für neue Zeile für Debugausgaben
#define TURAG_DEBUG_NEWLINE "\n"

#define TURAG_WORDSIZE 32

#define TURAG_ATTR_SECTION_CCMDATA ATTR_SECTION_CCMDATA


#endif // PLATFORM_CHIBIOS3_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H
