#ifndef TURAG_FELDBUS_FUER_ASEB_H_
#define TURAG_FELDBUS_FUER_ASEB_H_

/* 
 * This header file contains the specification for the protocol
 * "TURAG-FeldBus für ASEB". Refer to the DokuWiki for documentation.
 */

#include "turag_feldbus_bus_protokoll.h"

// device types
#define TURAG_FELDBUS_ASEB_GENERIC		0x01


// channel index range
#define TURAG_FELDBUS_ASEB_MAX_CHANNELS_PER_TYPE		16
#define TURAG_FELDBUS_ASEB_INDEX_START_DIGITAL_INPUT	1
#define TURAG_FELDBUS_ASEB_INDEX_START_ANALOG_INPUT		17
#define TURAG_FELDBUS_ASEB_INDEX_START_DIGITAL_OUTPUT	33
#define TURAG_FELDBUS_ASEB_INDEX_START_PWM_OUTPUT		49


// commands
#define TURAG_FELDBUS_ASEB_SYNC							0xff
#define TURAG_FELDBUS_ASEB_CHANNEL_NAME					245
#define TURAG_FELDBUS_ASEB_CHANNEL_NAME_LENGTH			246
#define TURAG_FELDBUS_ASEB_NUMBER_OF_DIGITAL_INPUTS		247
#define TURAG_FELDBUS_ASEB_NUMBER_OF_DIGITAL_OUTPUTS	248
#define TURAG_FELDBUS_ASEB_NUMBER_OF_ANALOG_INPUTS		249
#define TURAG_FELDBUS_ASEB_ANALOG_INPUT_RESOLUTION		250
#define TURAG_FELDBUS_ASEB_ANALOG_INPUT_FACTOR			251
#define TURAG_FELDBUS_ASEB_NUMBER_OF_PWM_OUTPUTS		252
#define TURAG_FELDBUS_ASEB_PWM_OUTPUT_FREQUENCY			253
#define TURAG_FELDBUS_ASEB_PWM_OUTPUT_MAX_VALUE			254


#endif
