/**
 *  @brief		TURAG-Feldbus für BMaX-Bootloader protocol definitions.
 *  @file		turag_feldbus_fuer_bootloader.h
 *  @date		21.02.2014
 *  @author		Florian Völker <flo-voelker@gmx.de>
 *  @ingroup	feldbus-protocol
 *
 */

#ifndef TURAG_FELDBUS_FUER_BOOTLOADER_H_
#define TURAG_FELDBUS_FUER_BOOTLOADER_H_


#include "turag_feldbus_bus_protokoll.h"

/**
 * @name Gerätetypen/Architekturen
 * @{
 */
#define TURAG_FELDBUS_BOOTLOADER_GENERIC				0x01
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA					0x02
#define TURAG_FELDBUS_BOOTLOADER_XMEGA  				0x03

///@}


/**
 * @name Allgemeine Commands
 * @{
 */
#define TURAG_FELDBUS_BOOTLOADER_COMMAND_GET_MCUID				0x01
#define TURAG_FELDBUS_BOOTLOADER_COMMAND_UNLOCK_BOOTLOADER		0x02

#define TURAG_FELDBUS_BOOTLOADER_COMMAND_ENTER_BOOTLOADER		0xA1
#define TURAG_FELDBUS_BOOTLOADER_COMMAND_START_PROGRAMM			0xAF

#define TURAG_FELDBUS_BOOTLOADER_UNLOCK_CODE					0x4266
#define TURAG_FELDBUS_BOOTLOADER_RESPONSE_UNLOCKED				0x00
#define TURAG_FELDBUS_BOOTLOADER_RESPONSE_UNLOCK_REJECTED		0x01

///@}


/**
 * @name Atmega Commans
 * @{
 */
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_GET_PAGE_SIZE			0x03
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_GET_FUSES				0x04
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_PAGE_WRITE				0xAA
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_DATA_READ				0xAB


#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_RESPONSE_SUCCESS			0x00
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_RESPONSE_FAIL_SIZE			0xFA
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_RESPONSE_FAIL_ADDRESS		0xFB
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_RESPONSE_FAIL_CONTENT		0xFD
#define TURAG_FELDBUS_BOOTLOADER_ATMEGA_RESPONSE_FAIL_UNSUPPORTED	0xFF
///@}



/**
 * @name MCU-IDs 
 * @{
 */
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA8				0x0793
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA32			0x0295
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA128			0x0297
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA88			0x0A93
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA168			0x0694
#define TURAG_FELDBUS_BOOTLOADER_MCU_ID_ATMEGA644			0x0996


///@}

#endif
