#ifndef PLATFORM_DESKTOP_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H
#define PLATFORM_DESKTOP_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H

/// ASCII-Zeichen für neue Zeile für Debugausgaben
#define TURAG_DEBUG_NEWLINE "\n"

#define TURAG_FELDBUS_AKTOR_STRUCTURED_OUTPUT_AVAILABLE 1

#define TURAG_USE_LIBSUPCPP_RUNTIME_SUPPORT 1

#define TURAG_PRINT_GAMETIME_AUTOMATIC 0


#endif // PLATFORM_DESKTOP_PUBLIC_TINA_CONFIG_TINA_PLATFORM_H
