#ifndef FELDBUS_CONFIG_CHECK_AVR_H_
#define FELDBUS_CONFIG_CHECK_AVR_H_


// hide some uninteresting stuff from documentation
#if (!defined(__DOXYGEN__))
    
#ifndef MY_ADDR
# error MY_ADDR must be defined
#endif
#ifndef TURAG_FELDBUS_DEVICE_NAME
# define TURAG_FELDBUS_DEVICE_NAME "unnamed device"
#endif
#ifndef TURAG_FELDBUS_DEVICE_VERSIONINFO
# define TURAG_FELDBUS_DEVICE_VERSIONINFO __DATE__ " " __TIME__
#endif
#ifndef TURAG_FELDBUS_DEVICE_PROTOCOL
# error TURAG_FELDBUS_DEVICE_PROTOCOL must be defined
#endif
#ifndef TURAG_FELDBUS_DEVICE_TYPE_ID
# error TURAG_FELDBUS_DEVICE_TYPE_ID must be defined
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH
# error TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH must be defined
#else
# if (TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH != 1 ) && (TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH != 2)
#  error TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH must be 1 or 2
# endif
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_CRC_TYPE
# error TURAG_FELDBUS_SLAVE_CONFIG_CRC_TYPE must be defined
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_BUFFER_SIZE
# error TURAG_FELDBUS_SLAVE_CONFIG_BUFFER_SIZE must be defined
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_DEBUG_ENABLED
# error TURAG_FELDBUS_SLAVE_CONFIG_DEBUG_ENABLED must be defined
#else
# if TURAG_FELDBUS_SLAVE_CONFIG_DEBUG_ENABLED
#  warning TURAG_FELDBUS_SLAVE_CONFIG_DEBUG_ENABLED = 1
# endif
#endif
#ifndef TURAG_FELDBUS_SLAVE_BROADCASTS_AVAILABLE
# error TURAG_FELDBUS_SLAVE_BROADCASTS_AVAILABLE must be defined
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY
# error TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY must be defined
#else
# if (TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY<0) || (TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY>65535)
#  error TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY must be within the range of 0-65535
# else
#  if TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY != 0 && !defined(TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK)
#   error TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK must be defined
#  endif
#  if TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY == 0 && !defined(TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK)
#   define TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK 0
#  endif
#  if TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY==0 && defined(TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK) && TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK != 0
#   warning TURAG_FELDBUS_SLAVE_CONFIG_USE_LED_CALLBACK == 1, but TURAG_FELDBUS_SLAVE_CONFIG_UPTIME_FREQUENCY == 0. Led flashing feature depends on uptime feature.
#  endif
# endif
#endif
#ifndef TURAG_FELDBUS_SLAVE_CONFIG_PACKAGE_STATISTICS_AVAILABLE
# error TURAG_FELDBUS_SLAVE_CONFIG_PACKAGE_STATISTICS_AVAILABLE must be defined
#endif


#if TURAG_FELDBUS_SLAVE_CONFIG_BUFFER_SIZE > 65535
# error buffer sizes greater than 65535 are no longer supported.
#elif TURAG_FELDBUS_SLAVE_CONFIG_BUFFER_SIZE > 255
    typedef uint16_t FeldbusSize_t;
# if TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH == 1
#  define TURAG_FELDBUS_IGNORE_PACKAGE 0xffff
# elif TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH == 2
#  define TURAG_FELDBUS_IGNORE_PACKAGE 0xfffe
# else
#  error no option for address size
# endif
#else
    typedef uint8_t FeldbusSize_t;
# if TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH == 1
#  define TURAG_FELDBUS_IGNORE_PACKAGE 0xff
# elif TURAG_FELDBUS_SLAVE_CONFIG_ADDRESS_LENGTH == 2
#  define TURAG_FELDBUS_IGNORE_PACKAGE 0xfe
# else
#  error no option for address size
# endif
#endif

#endif


#endif // FELDBUS_CONFIG_CHECK_AVR_H_