#ifndef TINA_SIM_CONFIG_H
#define TINA_SIM_CONFIG_H

/// ASCII-Zeichen für neue Zeile für Debugausgaben
#define TURAG_DEBUG_NEWLINE "\n"

#define TURAG_FELDBUS_AKTOR_STRUCTURED_OUTPUT_AVAILABLE

#define TURAG_LIBSTDCPP_SUPPORT


#endif // TINA_SIM_CONFIG_H
