#ifndef TINA_CONFIG_TINA_PLATFORM_H
#define TINA_CONFIG_TINA_PLATFORM_H

/// ASCII-Zeichen für neue Zeile für Debugausgaben
#define TURAG_DEBUG_NEWLINE "\n"

#define TURAG_FELDBUS_AKTOR_STRUCTURED_OUTPUT_AVAILABLE 1

#define TURAG_USE_LIBSUPCPP_RUNTIME_SUPPORT 1


#endif // TINA_CONFIG_TINA_PLATFORM_H
