#ifndef PLATFORM_DESKTOP_PUBLIC_TINA_TIMETYPE_H
#define PLATFORM_DESKTOP_PUBLIC_TINA_TIMETYPE_H

#include <stdint.h>

typedef uint64_t TuragSystemTicks;

#endif // PLATFORM_DESKTOP_PUBLIC_TINA_TIMETYPE_H
