#ifndef PLATFORM_ROS_INCLUDE_CONFIG_TINA_H
#define PLATFORM_ROS_INCLUDE_CONFIG_TINA_H

#define TURAG_CRC_CRC8_ALGORITHM            1
#define TURAG_CRC_INLINED_CALCULATION       1
#define TURAG_USE_TURAG_FELDBUS_HOST        1
#define TURAG_USE_TINA_HIGH_RES_DELAY_TIMER 1
#define TURAG_USE_STD_FUNCTION              1

#define TURAG_UNITS_REAL_TYPE               double
#define TURAG_UNITS_VALUE_TYPE              double
#define TURAG_UNITS_FACTOR_TO_METER         1.0
#define TURAG_UNITS_FACTOR_TO_RADIAN        1.0
#define TURAG_UNITS_FACTOR_TO_SECOND        1.0
#define TURAG_UNITS_FACTOR_TO_KILOGRAMM     1.0
#define TURAG_UNITS_FACTOR_TO_AMPERE        1.0

#endif // PLATFORM_ROS_INCLUDE_CONFIG_TINA_H
